name: Blog CI

on:
  push:
    tags:
      - "*-build"

jobs:
  build:
    name: Build Docker image and auto deploy
    runs-on: ubuntu-latest

    env:
      ALGOLIA_APPID: ${{ secrets.ALGOLIA_APPID }}
      ALGOLIA_APIKEY: ${{ secrets.ALGOLIA_APIKEY }}
      ALGOLIA_ADMINAPIKEY: ${{ secrets.ALGOLIA_ADMINAPIKEY }}


    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Hexo environment
        run: |
          echo "export ALGOLIA_APPID=${ALGOLIA_APPID}" >> $GITHUB_ENV
          echo "export ALGOLIA_APIKEY=${ALGOLIA_APIKEY}" >> $GITHUB_ENV
          echo "export ALGOLIA_ADMINAPIKEY=${ALGOLIA_ADMINAPIKEY}" >> $GITHUB_ENV

      - name: Get Tag
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            registry.cn-shanghai.aliyuncs.com/allbug-blog/blog

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Hexo
        run: npm install hexo -g

      - name: Install dependencies
        run: npm install

      - name: Generate Blog
        run: hexo g

      - name: Login Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ALIYUN_USER }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}